backend:
  name: github
  repo: dreitagebart/dreitagebart.io

site_url: https://www.dreitagebart.io
publish_mode: editorial_workflow
media_folder: content/assets
public_folder: ../assets

collections:
  - name: blog
    label: Blog
    folder: content/blog
    create: true
    fields:
      - { name: path, label: Slug }
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: description, label: Description }
      - { name: body, label: Body, widget: markdown }
