backend:
  name: github
  repo: dreitagebart/dreitagebart.io

media_folder: static/images/uploads
public_folder: ../assets

collections:
  - name: blog
    label: Blog
    folder: src/assets/markdown
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: description, label: Description }
      - { name: body, label: Body, widget: markdown }
